### PR TITLE
Add support for predefined constants in crontab files

### PR DESCRIPTION
**Pull request by lra**
See `Nonstandard predefined scheduling definitions` in http://en.wikipedia.org/wiki/Cron

Also support all type of env vars in crontab files.

### CODE REVIEW

**Comment by aegypius** [comment]
Thanks for you contribution @Ira, could you update specs to cover your changes ?

**Comment by lra** [comment]
Sure, I'm totally new to this, can you point me to a doc that describes what those spec are about?

**Comment by aegypius** [comment]
To be totally honest this package is actually my first too with specs. It may not be the best approach but you can check the existing one in the repository. It's heavily inspired by official languages package in atom repository.

I can't point you to the docs, I never put my hands on it 😕

**Comment by aegypius** [comment]
Sorry @lra, I totally forgot to check this PR, It as been merged and released in v0.2.0

**Pull request merged**
